### ISSUE TITLE
GetxController cannot be tested using unit testing and mocktail

### ISSUE THREAD

**Issue by darwin-morocho** [jonataslaw/getx#1629]
Hi, I am using `get: 4.1.4` and `mocktail: ^0.1.4` to write a simple unit test but I am having the next error.

`type 'Null' is not a subtype of type '_InternalFinalCallback<void>'`

Here my controller
```dart
class SplashController extends GetxController {
  final FirebaseAuthService _authService = Get.find<FirebaseAuthService>();
  final ComplianceService _complianceService = Get.find<ComplianceService>();
  final MarketService _marketService = Get.find<MarketService>();

  /// string to save the route name to navigate
  String? _routeName;
  String? get routeName => _routeName;

  /// stream controller to emit errors as a string
  final _errors = StreamController<String>();
  Stream<String> get onErrors => _errors.stream;

  @override
  void onClose() {
    _errors.close();
    super.onClose();
  }
}

```

Mocks , also all services extends from  GetxService

```dart
class MockComplianceService extends Mock implements ComplianceService {}
class MockFirebaseAuthService extends Mock implements FirebaseAuthService {}
class MockMarketService extends Mock implements MarketService {}
```

Unit test
```dart

void main() {
  setUp(() {
    Get.reset();

    Get.create<FirebaseAuthService>(
      () => MockFirebaseAuthService(),
    );
    Get.create<ComplianceService>(
      () => MockComplianceService(),
    );
    Get.create<MarketService>(
      () => MockMarketService(),
    );
    Get.create<SplashController>(
      () => SplashController(),
    );
  });

  test('SplashController > default values', () {
    final controller = SplashController();
    /// by default routeName must be null
    expect(controller.routeName, isNull);
  });
}
```

Expected behavior
The unit test will pass

**Comment by darwin-morocho** [comment]
@jonataslaw any solution for this?

**Comment by jonataslaw** [comment]
> @jonataslaw any solution for this? Thanks for the answer

You can use the master if it's urgent, this problem has already been solved on the master.
I haven't uploaded to pub.dev yet, because I'm analyzing changes for the GetX release with nav2 (which is also in master) and will upload when I'm sure no api will change, to avoid crashing.

If it's something extremely urgent, you can use:

```yaml
dependencies:
   plugin1:
     git:
       url: git://github.com/jonataslaw/getx.git
```

I believe this weekend the master version will be packaged on pub.dev

**Comment by jonataslaw** [comment]
Since this was fixed 3 releases ago, I'm closing this

**Comment by darwin-morocho** [comment]
> Since this was fixed 3 releases ago, I'm closing this

I've update to `get: ^4.3.0` and running the same unit test again and I am still having the same error.
![image](https://user-images.githubusercontent.com/15864336/127557019-6542ca2a-addf-422a-ac85-723874befb78.png)

**Comment by jonataslaw** [comment]
Have you tried to extend GetxService/GetxController? Something like:

```dart
class MockComplianceService extends GetxService with Mock implements ComplianceService {}
``` 
?

**Comment by darwin-morocho** [comment]
> Have you tried to extend GetxService/GetxController? Something like:
> 
> ```dart
> class MockComplianceService extends GetxService with Mock implements ComplianceService {}
> ```
> 
> ?

No,  I haven't. I will try it.

**Comment by darwin-morocho** [comment]
> > Have you tried to extend GetxService/GetxController? Something like:
> > ```dart
> > class MockComplianceService extends GetxService with Mock implements ComplianceService {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?
> 
> No, I haven't. I will try it.

Now it's working

**Comment by jonataslaw** [comment]
Thanks for the feedback, I'll try to insert this in the readme or some other place that's easier to access.

**Comment by Gokul-Oak-Coder** [comment]
Thanks in Advance, could you somebody help me on the GetX Unit test in on a clean architecture flutter project which uses GetBuilder fro the update(), need to write on a controller classes.
