### ISSUE TITLE
[5.0 RC] Redirect is not working

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#2713]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
1. With 2 pages, Home page which is guarded by EnsureAuthMiddleware and Login page which is guarded by EnsureNotAuthedMiddleware. 
2. The initial route set to Home page.
3. When running app, expect it will end with the Login page, but it ends with the Home page.

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
class EnsureAuthMiddleware extends GetMiddleware {
  @override
  RouteSettings? redirect(String? route) {
    return App.identity.isAuthenticated
        ? null
        : const RouteSettings(name: AppRoutes.login);
  }
}

class EnsureNotAuthedMiddleware extends GetMiddleware {
  @override
  RouteSettings? redirect(String? route) {
    return !App.identity.isAuthenticated
        ? null
        : const RouteSettings(name: AppRoutes.home);
  }
}

class AppPages {
  AppPages._();

  // ignore: constant_identifier_names
  static const INITIAL = _Paths.home;

  static final routes = [
    GetPage(
        middlewares: [EnsureAuthMiddleware()],
        name: _Paths.home,
        page: () => const HomeView(),
        bindings: [HomeBinding()],
        children: [
          GetPage(
            name: _Paths.dashboard,
            page: () => const DashboardView(),
            bindings: [DashboardBinding()],
          )
        ]),
    GetPage(
      middlewares: [EnsureNotAuthedMiddleware()],
      name: _Paths.login,
      page: () => LoginView(),
      bindings: [LoginBinding()],
    ),
    GetPage(
      name: '/404',
      page: () => const NotFoundPage(),
    ),
  ];
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      builder: App.builder,
      title: 'Kilikalak | VIQCore',
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
    );
  }
}
```

**Expected behavior**
Expect redirection correctly route to login page.

**Screenshots**

![redirect_issue](https://user-images.githubusercontent.com/107820/221404023-96fb1542-ef03-4feb-9f52-d03efe4079fd.gif)

**Flutter Version:**
3.7.3

**Getx Version:**
[5.0.0-release-candidate](https://pub.dev/packages/get/versions/5.0.0-release-candidate)

**Describe on which device you found the bug:**
Flutter Web

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jasonlaw** [comment]
UPDATE:

The redirection is not working even after I remove the guard for login page.

![image](https://user-images.githubusercontent.com/107820/221407523-39fea95e-436e-4c09-a994-82efa2f86a0b.png)

**Comment by tuananhdldev** [comment]
In 5.0 RC, change theme is not work by Get.changeTheme(), please fix it

**Comment by jonataslaw** [comment]
I think the api change a little bit, and the changes are not documented yet. 

I will rename redirectDelegate to redirect, but I think that something like this will work:

class EnsureAuthMiddleware extends GetMiddleware {
  @override
  Future<RouteDecoder?> redirectDelegate(RouteDecoder route) async {

    if (!AuthService.to.isLoggedInValue) {
      return RouteDecoder.fromRoute(AppRoutes.login);
    }
    return await super.redirectDelegate(route);
  }
}

class EnsureNotAuthedMiddleware extends GetMiddleware {
  @override
  Future<RouteDecoder?> redirectDelegate(RouteDecoder route) async {
    if (AuthService.to.isLoggedInValue) {
      //NEVER navigate to auth screen, when user is already authed
      return null;
    }
    return await super.redirectDelegate(route);
  }
}

**Comment by jonataslaw** [comment]
> In 5.0 RC, change theme is not work by Get.changeTheme(), please fix it

It is fixed in RC.3

**Comment by jasonlaw** [comment]
> I think the api change a little bit, and the changes are not documented yet.
> 
> I will rename redirectDelegate to redirect, but I think that something like this will work:
> 
> ```dart
> class EnsureAuthMiddleware extends GetMiddleware {
>   @override
>   Future<RouteDecoder?> redirectDelegate(RouteDecoder route) async {
> 
>     if (!AuthService.to.isLoggedInValue) {
>       return RouteDecoder.fromRoute(AppRoutes.login);
>     }
>     return await super.redirectDelegate(route);
>   }
> }
> 
> class EnsureNotAuthedMiddleware extends GetMiddleware {
>   @override
>   Future<RouteDecoder?> redirectDelegate(RouteDecoder route) async {
>     if (AuthService.to.isLoggedInValue) {
>       //NEVER navigate to auth screen, when user is already authed
>       return null;
>     }
>     return await super.redirectDelegate(route);
>   }
> }
> ```

@jonataslaw Thanks for the reply, it works with the new api. So now Getx 5.0 will be using Nav 2.0 by default, in this case, may I know if Get.offAllNamed is still working? 

In my case, I wish to use Get.offAllNamed after login, so that user will not be abled to "back" to the login page. It seems not possible to do this now, am I missing something?

Thank you!

**Comment by jasonlaw** [comment]
> > In 5.0 RC, change theme is not work by Get.changeTheme(), please fix it
> 
> It is fixed in RC.3

I have tested the Get.changeTheme() in RC.3 and it seems still not working. :(

**Comment by jasonlaw** [comment]
Get.changeTheme() is working fine now with RC.4.
Looking forward others to work fine in the coming release.
Thanks.

**Comment by gauravmehta13** [comment]
@jonataslaw  Can you please deprecate or remove onRedirect if we are going to use redirectDelegate, Since its not working.
