### ISSUE TITLE
RTL directionality support

### ISSUE THREAD

**Issue by smokelaboratory** [jonataslaw/getx#600]
Wonderful package!
Is there a way to change layout direction for RTL languages when using GetX translations?

**Comment by roipeker** [comment]
Thanks for noticing that @smokelaboratory ! 
I didn't try the internationalisation capabilities of GetX™ until now.
I just pushed a fix to refresh the UI when you `Get.changeLocale()`, and included in the docs and [README](https://github.com/jonataslaw/getx/blob/7754903adb000ae3712ccad4e07b4922ef323c30/README.md#locales).
Please, give it a try when it gets merged, and let me know if the issue is solved.

**Comment by Hamidrezana** [comment]
@roipeker 

I have same issue, and I try what you included in README, but still have issue.
layout does not update on changing locale, but update after after hot reload.

```
  Widget build(BuildContext context) {
    return StoreProvider<AppState>(
      store: store,
      child: AppThemeProvider(
        child: (themeContext) => GetMaterialApp(
          title: Strings.appName,
          debugShowCheckedModeBanner: false,
          localizationsDelegates: [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          translations: Translation(),
          locale: Locale('fa', 'IR'),
          fallbackLocale: Locale('en', 'US'),
          supportedLocales: [Locale('fa', 'IR'), Locale('en', 'US')],
          popGesture: true,
          theme: ThemeProvider.themeOf(themeContext).data,
          home: InitialApp(),
        ),
      ),
    );
  }
```

**Comment by smokelaboratory** [comment]
@Hamidrezana 

I think the change is not yet merged. It is under review.
Here is the PR for it (https://github.com/jonataslaw/getx/pull/601)

**Comment by Hamidrezana** [comment]
@smokelaboratory tnx.

**Comment by jonataslaw** [comment]
closed by https://github.com/jonataslaw/getx/commit/ccf017823a0b3bb41bccec11653d54dc29015579

**Comment by roipeker** [comment]
wonderful approach

**Comment by virodveloper** [comment]
Hy  here is the temporary fix To Change Language using GetX utils(RTL and LTR)
Step 1 : import flutter_localizations SDK
Step 2 : Make your MyApp base Widget to stateful
Step 3 : Write these lines in MyApp base widget
static void setLocale(BuildContext context,Locale locale){
  final _MyAppState state=context.findAncestorStateOfType<_MyAppState>();
  state.setLocale(locale);
Step 4 : And these Lines in _MyAppState Widget
void setLocale(Locale locale){
  setState(() {
    _locale=locale;
  });
}
Locale _locale;
Step 5 : Add these lines in GetMaterialApp
locale: _locale??_setLanguage(),
localeResolutionCallback: (deviceLocale,supportedLocale){
  for(final locale in supportedLocale){
    if(locale.languageCode==deviceLocale.languageCode&&locale.countryCode==deviceLocale.countryCode){
      return deviceLocale;
    }
  }
  return supportedLocale.first;
},
localizationsDelegates: [
  GlobalCupertinoLocalizations.delegate,
  GlobalMaterialLocalizations.delegate,
  GlobalWidgetsLocalizations.delegate,
],
supportedLocales: <Locale>[Locale('en', 'UK'),  Locale('en', 'US'), Locale('ar','AE')],
Step 6 : Write This Function in your main
Locale _setLanguage() {
  Locale _locale;
  final _box = Hive.box(kConfigDBKey);//kConfigDBKey is Db key to store user select lang
  final String _language = _box.get(kConfigBoxFieldLang).toString();//kConfigBoxFieldLang is variable Key to get user selected lang
  switch (_language) {
    case 'ar':
      _locale = const Locale('ar', 'AE');
      break;
    case 'en':
      _locale = const Locale('en', 'US');
      break;
    default:
      _locale = const Locale('en', 'US');
  }
  return _locale;
}
Step 7 : Invoke Base Widget My App from the button you want to changes App Language(note context is Build context you can pass it in function parameters and then to the invocation)
MyApp.setLocale(context, _locale);
Get.updateLocale(_locale);

**Comment by Hamidrezana** [comment]
@jonataslaw  Has this update been released?

**Comment by Nipodemos** [comment]
> Has this update been released?

not yet @Hamidrezana

**Comment by Hamidrezana** [comment]
@jonataslaw I still have problem after upgrading to new version and layout doesn't update.

**Comment by virodveloper** [comment]
Hy i have updated a patch in Get slack channel Utils section for RtL layoit
changes.
Please have a look at it

**Comment by mohadel92** [comment]
any news about RTL support?

**Comment by adnankhan74444** [comment]
any update on RTL ?
